---
# Helper playbook to detect Proxmox storage configuration
- name: Detect Proxmox Storage
  hosts: proxmox
  become: true
  gather_facts: false

  tasks:
    - name: List available storage
      ansible.builtin.command: pvesm status
      register: storage_status
      changed_when: false

    - name: Display storage information
      ansible.builtin.debug:
        msg: "{{ storage_status.stdout_lines }}"

    - name: Get detailed storage info
      ansible.builtin.shell: |
        echo "=== Storage Configuration ==="
        pvesm status -content images
        echo ""
        echo "=== Recommended storage for OPNsense ==="
        pvesm status -content images | awk 'NR>1 {print $1}' | head -1
      register: storage_detail
      changed_when: false

    - name: Show recommendation
      ansible.builtin.debug:
        msg: |
          {{ storage_detail.stdout }}
          
          To use this storage, set in your environment:
          export OPNSENSE_STORAGE="<storage-name-from-above>"
          
          Or run:
          OPNSENSE_STORAGE="<storage-name>" make opnsense-cloudinit-template
