- name: Fetch and Prepare OPNsense ISO
  hosts: proxmox
  become: true
  vars:
    mirror_base: "https://mirror.ams1.nl.leaseweb.net/opnsense/releases"
    iso_path: "/var/lib/vz/template/iso"

  tasks:
    - name: Ensure dependency 'bzip2' is installed
      ansible.builtin.apt:
        name: bzip2
        state: present

    - name: Detect latest OPNsense version
      ansible.builtin.shell: |
        curl -s {{ mirror_base }}/ | grep -oP 'href="\K[0-9]+\.[0-9]+(?=/")' | sort -V | tail -n1
      register: latest_version_out
      changed_when: false

    - name: Set version fact
      ansible.builtin.set_fact:
        opnsense_ver: "{{ latest_version_out.stdout }}"
        final_iso: "{{ iso_path }}/OPNsense-{{ latest_version_out.stdout }}-dvd-amd64.iso"

    - name: Check if ISO already exists
      ansible.builtin.stat:
        path: "{{ final_iso }}"
      register: iso_check

    - name: Display detected version
      ansible.builtin.debug:
        msg: "🔎 Detected: {{ opnsense_ver }} | Exists? {{ iso_check.stat.exists }}"

    - name: Download and Prepare ISO
      when: not iso_check.stat.exists
      block:
        - name: Download OPNsense ISO (Compressed)
          ansible.builtin.get_url:
            url: "{{ mirror_base }}/{{ opnsense_ver }}/OPNsense-{{ opnsense_ver }}-dvd-amd64.iso.bz2"
            dest: "{{ final_iso }}.bz2"
            mode: '0644'

        - name: Decompress ISO
          ansible.builtin.shell: |
            bzip2 -d -k -f {{ final_iso }}.bz2

        - name: Cleanup compressed file
          ansible.builtin.file:
            path: "{{ final_iso }}.bz2"
            state: absent

    - name: Save ISO Path to .envrc for Terraform
      ansible.builtin.blockinfile:
        path: "{{ playbook_dir }}/../.envrc"
        marker: "# {mark} ANSIBLE MANAGED ISO VAR"
        block: |
          export TF_VAR_opnsense_iso="local:iso/OPNsense-{{ opnsense_ver }}-dvd-amd64.iso"
      delegate_to: localhost
      become: false

    - name: Auto-approve .envrc changes
      ansible.builtin.command: direnv allow "{{ playbook_dir }}/.."
      delegate_to: localhost
      become: false
      changed_when: true
