- name: Configure Network Bridges
  hosts: proxmox
  become: true
  
  tasks:
    - name: Ensure vmbr1 (LAN Bridge) exists in /etc/network/interfaces
      ansible.builtin.blockinfile:
        path: /etc/network/interfaces
        marker: "# {mark} ANSIBLE MANAGED: LAN BRIDGE"
        block: |
          auto vmbr1
          iface vmbr1 inet manual
              bridge-ports none
              bridge-stp off
              bridge-fd 0
              comment Internal LAN (Managed by Ansible)
      register: net_config

    - name: Apply Network Changes (if needed)
      ansible.builtin.command: ifreload -a
      when: net_config.changed
      changed_when: true
