---
# Reconfigure OPNsense LAN IP post-boot (after the OPNsense VM is cloned from template and installed)
- name: Configure OPNsense LAN network
  hosts: opnsense
  gather_facts: false
  vars:
    opnsense_lan_ip: "{{ lookup('env', 'OPNSENSE_LAN_IP') | default('10.0.0.1', true) }}"
    opnsense_lan_mask: "{{ lookup('env', 'OPNSENSE_LAN_MASK') | default('24', true) }}"
    opnsense_config_path: "/conf/config.xml"
    opnsense_python: "/usr/local/bin/python3"

  pre_tasks:
    - name: Wait for SSH on OPNsense (default LAN 192.168.1.1)
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ ansible_port | default(22) }}"
        timeout: 180
        state: started
      delegate_to: localhost
      become: false

  tasks:
    - name: Back up current config.xml
      ansible.builtin.raw: "cp {{ opnsense_config_path }} {{ opnsense_config_path }}.bak-$(date +%Y%m%d%H%M%S)"
      changed_when: true

    - name: Update LAN IP and subnet in config.xml
      ansible.builtin.raw: |
        {{ opnsense_python }} - <<'PY'
        import xml.etree.ElementTree as ET

        path = "{{ opnsense_config_path }}"
        target_ip = "{{ opnsense_lan_ip }}"
        target_mask = "{{ opnsense_lan_mask }}"

        tree = ET.parse(path)
        root = tree.getroot()
        lan = root.find("./interfaces/lan")
        if lan is None:
            raise SystemExit("LAN interface not found in config.xml")

        changed = False

        ip_node = lan.find("ipaddr")
        if ip_node is None:
            ip_node = ET.SubElement(lan, "ipaddr")
        if ip_node.text != target_ip:
            ip_node.text = target_ip
            changed = True

        subnet_node = lan.find("subnet")
        if subnet_node is None:
            subnet_node = ET.SubElement(lan, "subnet")
        if subnet_node.text != target_mask:
            subnet_node.text = target_mask
            changed = True

        if changed:
            tree.write(path)
            print("updated")
        PY
      register: lan_update
      changed_when: "'updated' in lan_update.stdout"
      failed_when: lan_update.rc != 0

    - name: Apply interface configuration (async to survive IP change)
      ansible.builtin.raw: /usr/local/etc/rc.reload_interfaces
      async: 60
      poll: 0
      changed_when: "'updated' in lan_update.stdout"
      when: "'updated' in lan_update.stdout"

    - name: Wait for new LAN IP to answer SSH
      ansible.builtin.wait_for:
        host: "{{ opnsense_lan_ip }}"
        port: "{{ ansible_port | default(22) }}"
        timeout: 180
        state: started
      delegate_to: localhost
      become: false
      when: "'updated' in lan_update.stdout"
