---
- name: Prepare OPNsense template from micro image
  hosts: proxmox
  become: true

  vars:
    opnsense_micro_url: "{{ lookup('env', 'OPNSENSE_MICRO_URL') | default('', true) }}"
    opnsense_base_mirror: "{{ lookup('env', 'OPNSENSE_MIRROR') | default('https://www.mirrorservice.org/sites/opnsense.org/releases/mirror', true) }}"
    opnsense_template_vmid: "{{ lookup('env', 'OPNSENSE_TEMPLATE_VMID') | default('9000', true) }}"
    opnsense_template_name: "{{ lookup('env', 'OPNSENSE_TEMPLATE_NAME') | default('opnsense-template', true) }}"
    opnsense_storage: "{{ lookup('env', 'OPNSENSE_STORAGE') | default('local-zfs', true) }}"
    opnsense_img_dir: "/var/lib/vz/template/qemu"

  pre_tasks:
    - name: Fetch nano image index from mirror (when URL not provided)
      ansible.builtin.uri:
        url: "{{ opnsense_base_mirror }}/"
        return_content: true
      register: opnsense_mirror_index
      when: opnsense_micro_url | length == 0

    - name: Collect OPNsense nano image candidates (when URL not provided)
      ansible.builtin.set_fact:
        opnsense_micro_candidates: "{{ opnsense_mirror_index.content | regex_findall('OPNsense-[0-9.]+-nano-amd64\\.img\\.bz2') }}"
      when: opnsense_micro_url | length == 0

    - name: Fail if no nano image candidates were found
      ansible.builtin.fail:
        msg: "No OPNsense *-nano-amd64.img.bz2 files found in {{ opnsense_base_mirror }}/; set OPNSENSE_MICRO_URL to a specific image or adjust the playbook."
      when:
        - opnsense_micro_url | length == 0
        - opnsense_micro_candidates | length == 0

    - name: Choose latest nano image candidate as micro filename
      ansible.builtin.set_fact:
        opnsense_micro_filename: "{{ opnsense_micro_candidates | sort | last }}"
      when:
        - opnsense_micro_url | length == 0
        - opnsense_micro_candidates | length > 0

    - name: Set OPNsense micro image URL from mirror (when URL not provided)
      ansible.builtin.set_fact:
        opnsense_micro_url: "{{ opnsense_base_mirror }}/{{ opnsense_micro_filename }}"
      when: opnsense_micro_url | length == 0

    - name: Fail if OPNsense micro image URL could not be determined
      ansible.builtin.fail:
        msg: "Unable to determine OPNsense micro image URL; set OPNSENSE_MICRO_URL or check mirror {{ opnsense_base_mirror }}"
      when: opnsense_micro_url | length == 0

  tasks:
    - name: Ensure image directory exists
      ansible.builtin.file:
        path: "{{ opnsense_img_dir }}"
        state: directory
        mode: "0755"

    - name: Download OPNsense micro image (compressed)
      ansible.builtin.get_url:
        url: "{{ opnsense_micro_url }}"
        dest: "{{ opnsense_img_dir }}/opnsense-micro.img.bz2"
        mode: "0644"
        force: false

    - name: Decompress OPNsense micro image
      ansible.builtin.command: "bunzip2 -f {{ opnsense_img_dir }}/opnsense-micro.img.bz2"
      args:
        creates: "{{ opnsense_img_dir }}/opnsense-micro.img"

    - name: Create OPNsense template VM shell
      ansible.builtin.command: >-
        qm create {{ opnsense_template_vmid }}
        --name {{ opnsense_template_name }}
        --memory 4096
        --cores 2
        --sockets 1
        --net0 virtio,bridge=vmbr0
        --net1 virtio,bridge=vmbr1
        --scsihw virtio-scsi-pci
        --ostype other
      register: qm_create
      failed_when:
        - "qm_create.rc != 0 and 'already exists' not in (qm_create.stderr | default(''))"

    - name: Import OPNsense disk into storage
      ansible.builtin.command: >-
        qm importdisk {{ opnsense_template_vmid }}
        {{ opnsense_img_dir }}/opnsense-micro.img
        {{ opnsense_storage }}
        --format raw
      register: qm_import
      changed_when: qm_import.rc == 0

    - name: Read qm config to inspect disks
      ansible.builtin.command: >-
        qm config {{ opnsense_template_vmid }}
      register: qm_config
      changed_when: false

    - name: Check if scsi0 disk is already present
      ansible.builtin.set_fact:
        opnsense_scsi0_present: "{{ 'scsi0:' in qm_config.stdout }}"

    - name: Extract imported disk volume from qm config when scsi0 is missing
      ansible.builtin.set_fact:
        opnsense_imported_volume: "{{ (qm_config.stdout_lines | select('match', '^unused[0-9]+:') | list | first).split(': ', 2)[1] }}"
      when:
        - not opnsense_scsi0_present
        - (qm_config.stdout_lines | select('match', '^unused[0-9]+:') | list | length) > 0

    - name: Fail if no disk volume could be determined when scsi0 is missing
      ansible.builtin.fail:
        msg: "No disk volume found in qm config; expected scsi0 or at least one unused* entry after import. Run 'qm config {{ opnsense_template_vmid }}' on Proxmox and adjust the playbook."
      when:
        - not opnsense_scsi0_present
        - (qm_config.stdout_lines | select('match', '^unused[0-9]+:') | list | length) == 0

    - name: Attach imported disk as scsi0 and set boot options (when scsi0 was missing)
      ansible.builtin.command: >-
        qm set {{ opnsense_template_vmid }}
        --scsihw virtio-scsi-pci
        --scsi0 {{ opnsense_imported_volume }}
        --boot order=scsi0
      register: qm_set
      changed_when: qm_set.rc == 0
      when: not opnsense_scsi0_present

    - name: Ensure boot order points to scsi0 (when scsi0 already present)
      ansible.builtin.command: >-
        qm set {{ opnsense_template_vmid }}
        --boot order=scsi0
      register: qm_boot
      changed_when: qm_boot.rc == 0
      when: opnsense_scsi0_present

    - name: Check if VM is already a template
      ansible.builtin.set_fact:
        opnsense_is_template: "{{ 'template: 1' in qm_config.stdout }}"

    - name: Convert VM to template
      ansible.builtin.command: >-
        qm template {{ opnsense_template_vmid }}
      register: qm_template
      changed_when: qm_template.rc == 0
      when: not opnsense_is_template

    - name: Remove OPNsense micro image artifacts after template creation
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ opnsense_img_dir }}/opnsense-micro.img"
        - "{{ opnsense_img_dir }}/opnsense-micro.img.bz2"
