---
- name: Clone OPNsense VM from template (full clone, no Terraform)
  hosts: proxmox
  become: true

  vars:
    opnsense_template_vmid: "{{ lookup('env', 'OPNSENSE_TEMPLATE_VMID') | default('9000', true) }}"
    opnsense_vmid: "{{ lookup('env', 'OPNSENSE_VMID') | default('100', true) }}"
    opnsense_name: "{{ lookup('env', 'OPNSENSE_NAME') | default('opnsense-router', true) }}"
    opnsense_target_node: "{{ lookup('env', 'OPNSENSE_TARGET_NODE') | default('pve', true) }}"

  tasks:
    - name: Check if OPNsense VM already exists
      ansible.builtin.command: >-
        qm status {{ opnsense_vmid }}
      register: opnsense_status
      failed_when: false
      changed_when: false

    - name: Skip clone when OPNsense VM already exists
      ansible.builtin.debug:
        msg: "OPNsense VM with VMID {{ opnsense_vmid }} already exists; skipping clone."
      when: opnsense_status.rc == 0

    - name: Perform full clone from OPNsense template
      ansible.builtin.command: >-
        qm clone {{ opnsense_template_vmid }} {{ opnsense_vmid }}
        --name {{ opnsense_name }}
        --full
        --target {{ opnsense_target_node }}
      register: qm_clone
      changed_when: qm_clone.rc == 0
      when: opnsense_status.rc != 0

    - name: Set basic VM options (autostart, description, boot)
      ansible.builtin.command: >-
        qm set {{ opnsense_vmid }}
        --onboot 1
        --boot order=scsi0
        --description "Managed by Ansible (full clone from {{ opnsense_template_vmid }})"
      register: qm_set
      changed_when: qm_set.rc == 0
      when: opnsense_status.rc != 0

    - name: Start OPNsense VM
      ansible.builtin.command: >-
        qm start {{ opnsense_vmid }}
      register: qm_start
      changed_when: qm_start.rc == 0
      when: opnsense_status.rc != 0
