---
# Fix OPNsense firewall to allow ICMP and basic connectivity
- name: Configure OPNsense firewall rules
  hosts: proxmox
  become: true
  gather_facts: false

  tasks:
    - name: Disable firewall on WAN interface temporarily
      ansible.builtin.shell: |
        qm guest exec 100 -- /bin/sh -c 'echo "set skip on vtnet0" | pfctl -f -'
      register: fw_skip
      changed_when: fw_skip.rc == 0
      failed_when: false

    - name: Enable firewall
      ansible.builtin.shell: |
        qm guest exec 100 -- pfctl -e
      register: fw_enable
      changed_when: fw_enable.rc == 0
      failed_when: false

    - name: Test ping from Proxmox
      ansible.builtin.command: ping -c 2 10.0.0.1
      register: ping_test
      changed_when: false
      failed_when: false

    - name: Display status
      ansible.builtin.debug:
        msg: |
          Ping test: {{ 'SUCCESS' if ping_test.rc == 0 else 'FAILED' }}
          
          {{ ping_test.stdout }}
          
          Try pinging from your laptop now: ping 10.0.0.1
