---
# Diagnose network connectivity issues
- name: Network connectivity diagnostics
  hosts: proxmox
  become: true
  gather_facts: true

  tasks:
    - name: Check IP forwarding
      ansible.builtin.command: sysctl net.ipv4.ip_forward
      register: ip_forward
      changed_when: false

    - name: Check route to OPNsense LAN
      ansible.builtin.command: ip route show 10.0.0.0/24
      register: route_check
      changed_when: false

    - name: Check if OPNsense responds from Proxmox
      ansible.builtin.command: ping -c 2 10.0.0.1
      register: ping_opnsense
      changed_when: false
      failed_when: false

    - name: Check OPNsense WAN IP
      ansible.builtin.command: ip neigh show 192.168.1.75
      register: opnsense_wan
      changed_when: false

    - name: Display diagnostics
      ansible.builtin.debug:
        msg: |
          === DIAGNOSTICS ===
          
          IP Forwarding: {{ ip_forward.stdout }}
          Route to 10.0.0.0/24: {{ route_check.stdout }}
          Ping to OPNsense: {{ 'OK' if ping_opnsense.rc == 0 else 'FAILED' }}
          OPNsense WAN ARP: {{ opnsense_wan.stdout }}
          
          === YOUR LAPTOP NEEDS ===
          
          The problem: Your ASUS router might not be honoring the static route.
          
          TEMPORARY FIX - Add route directly on your laptop:
          
          Linux/Mac:
            sudo ip route add 10.0.0.0/24 via 192.168.1.75
            # OR on Mac:
            sudo route add -net 10.0.0.0/24 192.168.1.75
          
          Windows:
            route ADD 10.0.0.0 MASK 255.255.255.0 192.168.1.75
          
          Then test: ping 10.0.0.1
          
          PERMANENT FIX:
          Double-check your ASUS router static route:
            - Network/Host IP: 10.0.0.0
            - Netmask: 255.255.255.0
            - Gateway: 192.168.1.75
            - Make sure it's ENABLED
            - Try rebooting the router
