---
# Create admin user for OPNsense web UI
- name: Create OPNsense admin user
  hosts: proxmox
  become: true
  gather_facts: false

  vars:
    opnsense_admin_user: "{{ lookup('env', 'OPNSENSE_ADMIN_USER') | default('admin', true) }}"
    opnsense_admin_password: "{{ lookup('env', 'OPNSENSE_ADMIN_PASSWORD') | default('opnsense', true) }}"
    opnsense_vm_id: "{{ lookup('env', 'OPNSENSE_VM_ID') | default('100', true) }}"

  tasks:
    - name: Get OPNsense LAN IP address
      ansible.builtin.shell: |
        qm guest exec {{ opnsense_vm_id }} -- ifconfig eth1 | jq -r '.["out-data"]' | grep 'inet ' | awk '{print $2}'
      register: opnsense_ip_result
      changed_when: false

    - name: Set OPNsense IP
      ansible.builtin.set_fact:
        opnsense_host: "{{ opnsense_ip_result.stdout | trim }}"

    - name: Create user creation script locally
      ansible.builtin.copy:
        dest: /tmp/create_opnsense_user.php
        content: |
          <?php
          require_once '/usr/local/etc/inc/config.inc';
          require_once '/usr/local/etc/inc/util.inc';
          require_once '/usr/local/etc/inc/auth.inc';
          
          $config = parse_config(true);
          
          // Remove existing admin user if it exists
          foreach ($config['system']['user'] as $idx => $user) {
              if ($user['name'] == '{{ opnsense_admin_user }}') {
                  unset($config['system']['user'][$idx]);
                  break;
              }
          }
          
          // Create new admin user
          $new_user = array();
          $new_user['name'] = '{{ opnsense_admin_user }}';
          $new_user['descr'] = 'Admin user created by Ansible';
          $new_user['scope'] = 'user';
          $new_user['groupname'] = 'admins';
          $new_user['password'] = crypt('{{ opnsense_admin_password }}', '$6$rounds=5000$saltsalt$');
          $new_user['uid'] = '2000';
          $new_user['priv'] = array('page-all');
          
          $config['system']['user'][] = $new_user;
          
          write_config('Created {{ opnsense_admin_user }} user via Ansible');
          echo "User {{ opnsense_admin_user }} created successfully\n";
          ?>
        mode: '0644'

    - name: Copy script to OPNsense
      ansible.builtin.command: |
        scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyJump=root@127.0.0.1 /tmp/create_opnsense_user.php root@{{ opnsense_host }}:/tmp/
      changed_when: true

    - name: Create admin user
      ansible.builtin.command: |
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -J root@127.0.0.1 root@{{ opnsense_host }} "/usr/local/bin/php /tmp/create_opnsense_user.php"
      register: user_create_result
      changed_when: "'successfully' in user_create_result.stdout"

    - name: Clean up script
      ansible.builtin.file:
        path: /tmp/create_opnsense_user.php
        state: absent

    - name: Display access information
      ansible.builtin.debug:
        msg: |
          ✅ OPNsense admin user configured!
          
          Web UI Access:
            URL: https://{{ opnsense_host }}
            Username: {{ opnsense_admin_user }}
            Password: {{ opnsense_admin_password }}
          
          To use different credentials, set environment variables:
            export OPNSENSE_ADMIN_USER="yourusername"
            export OPNSENSE_ADMIN_PASSWORD="your-secure-password"
            make opnsense-set-password
